workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: latest
      groups:
        - firebase_vars
        - signing_vars
        #- google_play
      vars:
        PACKAGE_NAME: "com.anonymous.PackingList"
#        EXPO_PUBLIC_API_KEY: $EXPO_PUBLIC_API_KEY
#        EXPO_PUBLIC_AUTH_DOMAIN: $EXPO_PUBLIC_AUTH_DOMAIN
#        EXPO_PUBLIC_PROJECT_ID: $EXPO_PUBLIC_PROJECT_ID
#        EXPO_PUBLIC_STORAGE_BUCKET: $EXPO_PUBLIC_STORAGE_BUCKET
#        EXPO_PUBLIC_MESSAGING_SENDER_ID: $EXPO_PUBLIC_MESSAGING_SENDER_ID
#        EXPO_PUBLIC_APP_ID: $EXPO_PUBLIC_APP_ID

   # triggering:
   #   events:
   #     - push
   #     - tag
   #     - pull_request
   #   branch_patterns:
   #     - pattern: main
   #       include: true
   #       source: true


    scripts:
        # EXPO_PUBLIC_ -alkuiset muuttujat tulee sijoittaa .env tiedostoon ennen prebuildia
      - name: Expo public environment variables
        script: | 
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_API_KEY=$EXPO_PUBLIC_API_KEY" >> $CM_BUILD_DIR/.env
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_AUTH_DOMAIN=$EXPO_PUBLIC_AUTH_DOMAIN" >> $CM_BUILD_DIR/.env
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_PROJECT_ID=$EXPO_PUBLIC_PROJECT_ID" >> $CM_BUILD_DIR/.env
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_STORAGE_BUCKET=$EXPO_PUBLIC_STORAGE_BUCKET" >> $CM_BUILD_DIR/.env
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_MESSAGING_SENDER_ID=$EXPO_PUBLIC_MESSAGING_SENDER_ID" >> $CM_BUILD_DIR/.env
          echo "REACT_NATIVE_PACKING_LIST_FIREBASE_APP_ID=$EXPO_PUBLIC_APP_ID" >> $CM_BUILD_DIR/.env
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up app/build.gradle
        script: | 
          mv ./support-files/build.gradle android/app
      - name: pre_build_script
        # ANDROID_FIREBASE_SECRET sisältää google-services.json tiedoston joka on oikeasti uploadausta
        script: | 
          #!/usr/bin/env sh
          export ESIMERKKI="esimerkki"
          set -e # exit on first failed command
          echo $ANDROID_FIREBASE_SECRET | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
        # keystoresta haetaan upload key jolla signataan bundle
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          # The following script creates key.properties file and stores the credentials in it.
          # 
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Debugging environment
        script: |    
          echo "Displaying key.properties contents:"
          cat "$FCI_BUILD_DIR/android/key.properties" || echo "Error: Unable to display key.properties"
          echo "Listing contents of /tmp directory:"
          ls -la /tmp || echo "Error: Unable to list /tmp directory"
          echo "Displaying keystore details:"
          ls -la /tmp/keystore.keystore || echo "Error: keystore file not found"
          echo "displaying FCI_BUILD_DIR"
          echo $FCI_BUILD_DIR
          echo "displaying CM_BUILD_DIR"
          echo $CM_BUILD_DIR
          echo "displaying EXPO_PUBLIC_AUTH_DOMAIN"
          echo $EXPO_PUBLIC_AUTH_DOMAIN
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              # UPDATED_BUILD_NUMBER=$BUILD_NUMBER
              echo "no build number found from google play"
              exit 1
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - jarno.tauriainen@gmail.com
        notify:
          success: true
          failure: true
#jsoni varmaan vaan suoraan variableen?
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true